version: "3"
services:
  web:
     image: "${DOCKER_IMAGE}"
     ports:
     - "8001-8002:80"
    deploy:   
     relicas: 2
    depends_on:
     - mysql
  mysql:
     image: kuttysuresh/private:mysql
     volumes:
     - db_data:/var/lib/mysql
     environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: mydatabase
volumes:
   db_data: {}
